name: Paper Reading
description: Template for documenting insights and purpose of reading a research paper.
title: "[Paper] <Paper Title> `<BibTeX>`"
labels:
  - Paper
  - Research
body:
  - type: input
    id: paper_title
    attributes:
      label: 📄 Paper Title
      description: Enter the title of the paper you are reading
      placeholder: Attention is All You Need

  - type: textarea
    id: reason
    attributes:
      label: 🧐 Why Read This Paper?
      description: Describe the purpose of reading this paper. What do you aim to learn or solve?
      placeholder: To understand the Transformer architecture and its applications in NLP.

  - type: input
    id: field
    attributes:
      label: 📚 Field of Research
      description: Specify the primary field or domain of the paper (e.g., NLP, Computer Vision, Graph Neural Networks)
      placeholder: Natural Language Processing (NLP)

  - type: textarea
    id: key_points
    attributes:
      label: ✨ Key Takeaways
      description: Summarize the key ideas or insights from the paper after reading.
      placeholder: Transformer replaces RNNs with self-attention, improving parallelization.

  - type: textarea
    id: bibtex
    attributes:
      label: 📑 BibTeX Entry
      description: Paste the BibTeX entry for the paper for future citation.
      placeholder: |
        @article{vaswani2017attention,
          title={Attention Is All You Need},
          author={Vaswani, Ashish and Shazeer, Noam and Parmar, Niki and Uszkoreit, Jakob and Jones, Llion and Gomez, Aidan N and Kaiser, Lukasz and Polosukhin, Illia},
          journal={Advances in neural information processing systems},
          volume={30},
          year={2017}
        }

  - type: textarea
    id: links
    attributes:
      label: 🔗 Links
      description: Add links to the paper, code, or any other relevant resources.
      placeholder: |
        - [Paper](https://arxiv.org/abs/1706.03762)
        - [Code](....)
